### ISSUE TITLE
Installation of PySyft with Python3.6 on MacOS

### ISSUE THREAD

**Issue by addy369** [OpenMined/PySyft#4037]
## Description
So when I am trying to build with source there is an issue while running the tests..
After cloning https://github.com/OpenMined/PySyft.git and running python setup.py install,I try running setup.py test. There is first a issue i.e . No module named 'crypten'. 
I install it manually but it says it supports python 3.7 and upwards only.(This is the problem probably)
So my question is whether people are able to use python3.6 for installation? I keep getting this error  "cannot import name 'onnx_converter' " while running setup.py test. Any workaround??

**Comment by gmuraru** [comment]
Currently, there is supported only ```Python >= 3.7```

**Comment by addy369** [comment]
Actually it isn't working with python 3.7 too
Can you please follow these steps
Create a virtual environment with Python 3.7
Install torch 1.4 and vison 0.5.0
Clone pysyft
Cd into directory
Run python setup.py
Run python setup.py test

**Comment by addy369** [comment]
I keep getting this error "cannot import name 'onnx_converter'  from crypten.nn and that makes sense because there is no onnx_converter defined there

**Comment by radusqrt** [comment]
I got the same error on Linux with Python 3.7.7.

**Problem:** Apparently, when you install **crypten** using "python -m pip install crypten" it doesn't create the same structure as here: https://github.com/facebookresearch/CrypTen/tree/master/crypten/nn

The only release is from Feb 5, before the commit (https://github.com/facebookresearch/CrypTen/commit/1aa8cedced113806e3b35f653bcd03f2cf364d6b#diff-901387c8cb64f231ab7b5bb4cad43497) which creates the file causing the error (onnx_converter.py): https://pypi.org/project/crypten/#history

**Solution:** I just hacked it by copying everything from here [1] to [2]. It works now, but we should modify the documentation, I guess.
[1]: https://github.com/facebookresearch/CrypTen/tree/master/crypten
[2]: ~/anaconda3/envs/pysyft/lib/python3.7/site-packages/crypten/

Let me know if you have any idea on how to automatically fix this issue instead of hacking it like I did above.

**Comment by addy369** [comment]
@gmuraru so the installation instructions are a bit outdated...I have also confirmed @radusqrt is right. Pip install crypten has a different structure than when cloning from the repo https://github.com/facebookresearch/CrypTen/tree/master/crypten. I can update the installation readme

**Comment by vingstar** [comment]
@radusqrt thank you, your solution works!  
And I think, just as mentioned by @addy369 , this issue should be fixed as soon as possible.

**Comment by RockyZhangHKU** [comment]
@addy369 Hi, I also meet the same error as you mentioned about the "cannot import name 'onnx_converter' from crypten.nn. So have you solved it?

**Comment by cereallarceny** [comment]
Hello! Just letting you know that we are no longer planning on supporting anything on the 0.2.x product line and that all work should be ported over to 0.3.x, which is considered a complete rebuild of PySyft. Because of that, I'll be closing this issue. If you feel this is a mistake, or if the issue actually applies to 0.3.x as well, please feel free to ping me on Slack and I'll reopen the issue.
