### ISSUE TITLE
Part 10: Federated Learning with Encrypted Gradient Aggregation (Bug found)

### ISSUE THREAD

**Issue by Krypton3** [OpenMined/PySyft#2758]
Hi, 

I was testing this tutorial with my own dataset. It's working fine till secure encrypted aggregation. However, I have found this error with my dataset. I have also followed the tutorial fully. It also shows the same error for secure encrypted aggregation. 

The error is the following:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-72-431a5695a2e8> in <module>()
>       5 for epoch in range(args.epochs):
>       6     print(f"Epoch {epoch + 1}")
> ----> 7     train(epoch)
>       8     # test()
>       9 
> 
> 8 frames
> /usr/local/lib/python3.6/dist-packages/syft/frameworks/torch/hook/hook_args.py in <lambda>(i)
>      32 backward_func = {
>      33     TorchTensor: lambda i: i.wrap(),
> ---> 34     torch.Tensor: lambda i: i.wrap(),
>      35     torch.nn.Parameter: lambda i: torch.nn.Parameter(data=i),
>      36     AutogradTensor: lambda i: AutogradTensor(data=i).on(i, wrap=False),
> 
> AttributeError: 'numpy.ndarray' object has no attribute 'wrap'

@iamtrask  @LaRiffle 
I would appreciate an explanation. Thank you.

**Comment by alejandrosame** [comment]
Hi there!

@iamtrask reported in the Slack group that the issue is due to the import of NumPy to execute log2 like shown in https://github.com/OpenMined/PySyft/blob/master/syft/frameworks/torch/tensors/interpreters/native.py#L741. 

Since NumPy can only run locally, it cannot be used for Federated Learning yet. The solutions for this error would be to either:
* Hook NumPy as another PySyft framework.
* Implement log2 in PyTorch.

Cheers!

**Comment by MarksASP95** [comment]
Hey, I'm not sure how to apply the solutions you provided, could you be more specific?

**Comment by MarksASP95** [comment]
This notebook works on version 0.1.13a1.

**Comment by alejandrosame** [comment]
Hi @MarksASP95!

Both solutions involve development. I'm currently working and documenting the NumPy integration [on this issue](https://github.com/OpenMined/PySyft./issues/2771).
