### ISSUE TITLE
Import syft after installing latest version (0.2.8)

### ISSUE THREAD

**Issue by xanderwallace85** [OpenMined/PySyft#4464]
## Description
After upgrading my PySyft from 0.2.7 to 0.2.8 I am not able to import syft anymore. Now I get _ImportError: cannot import name 'ReduceOp' from 'torch.distributed'_.

## How to Reproduce
1. After installing PySyft 0.2.8
2. I import syft
3. As a consequence, I get _ImportError: cannot import name 'ReduceOp' from 'torch.distributed'_

## Expected Behavior
Import syft without errors.

## System Information
 - OS: Windows
 - OS Version: 10
 - Language Version: Python 3.8.3

**Comment by xanderwallace85** [comment]
> Use Python 3.6-3.7 and see if the error persists!

Hi @addy369, with 3.7 it worked! :)
Thank you so much for the precious help!

**Comment by addy369** [comment]
You can close the issue now
