### ISSUE TITLE
Should we support Python <3.8?

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3826]
## Question
Given that we want to use typing to enforce code style across the codebase and some of these typing features only exist in python 3.8, should we support any lesser versions?

## Further Information
At present, our tests don't build with Python 3.7 with some sort of error like 

```
=================================== ERRORS ===================================
__________ ERROR collecting tests/syft/typecheck/typecheck_test.py ___________
ImportError while importing test module '/Users/atrask/Dropbox/Laboratory/openmined/PySyft/PySyft/tests/syft/typecheck/typecheck_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/atrask/opt/anaconda3/lib/python3.7/site-packages/_pytest/python.py:493: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/Users/atrask/opt/anaconda3/lib/python3.7/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/Users/atrask/opt/anaconda3/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:143: in exec_module
    exec(co, module.__dict__)
tests/syft/typecheck/typecheck_test.py:2: in <module>
    from typing import List, Union, Optional, Tuple, Dict, DefaultDict, TypedDict
E   ImportError: cannot import name 'TypedDict' from 'typing' (/Users/atrask/opt/anaconda3/lib/python3.7/typing.py)
```

which is related to https://github.com/OpenMined/PySyft/issues/3722

**Comment by gmuraru** [comment]
As long as we do not have any framework related dependency (Torch, Tensorflow, CrypTen, etc.) that we need to support, I think we should try to support the latest version.

Using the type annotations will help us maintain a cleaner codebase by enforcing more specific restrictions that exist only in Python 3.8

**Comment by tudorcebere** [comment]
If it's not a blocker to other libraries, I am totally into 3.8. We can those features when syft 0.3 is done if we want backwards compatibility.

**Comment by madhavajay** [comment]
Resolved by https://github.com/OpenMined/PySyft/pull/3935
