### ISSUE TITLE
CONTRIBUTING.md incorrectly states python 3.6 as requirement

### ISSUE THREAD

**Issue by dylanamiller** [OpenMined/PySyft#5019]
## Where?
CONTRIBUTING.md

## Who?
The audience consists of individuals like myself who are looking to get into contributing to pysyft.

## What?
Correctly specify the python version required for the contribution instructions to run correctly.

## Additional Context
CONTRIBUTING.md lists python 3.6+ as a requirement, but recent updates to certain files, specifically those attempting to use `asyncio` only work in python 3.7+. This causes `pre-commit run --all-files` to fail on `mypy`.

`Trim Trailing Whitespace.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for added large files..............................................Passed
Check Yaml...............................................................Passed
Debug Statements (Python)................................................Passed
Tests should end in _test.py.............................................Passed
Fix requirements.txt.....................................................Passed
flake8...................................................................Passed
black....................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

src/syft/decorators/typecheck.py:11: error: Module 'typing' has no attribute 'ForwardRef'
src/syft/grid/connections/webrtc.py:108: error: Module 'asyncio' has no attribute 'get_running_loop'; maybe "_get_running_loop" or "_set_running_loop"?
src/syft/grid/connections/webrtc.py:406: error: Module has no attribute "run"
src/syft/grid/connections/webrtc.py:529: error: Module has no attribute "run"
src/syft/grid/connections/webrtc.py:559: error: Module has no attribute "run"
src/syft/lib/python/int.py:336: error: "as_integer_ratio" undefined in superclass
src/syft/lib/python/bool.py:275: error: "bool" has no attribute "as_integer_ratio"
src/syft/grid/duet/webrtc_duet.py:126: error: Module has no attribute "run"
src/syft/grid/duet/webrtc_duet.py:263: error: Module has no attribute "run"
src/syft/grid/duet/webrtc_duet.py:299: error: Module has no attribute "run"
Found 10 errors in 5 files (checked 216 source files)

flynt....................................................................Passed`

I am unsure as of yet if there are other issues like this one in the documentation, but as I finish up the process I will make note

**Comment by dylanamiller** [comment]
I will make this quick update to the documentation if that is alright.

**Comment by madhavajay** [comment]
@dylanamiller Python 3.6 is correctly listed and supported. I wonder if there is an issue with your local environment and running the pre-commit hook checks?

The version for mypy listed in the `.pre-commit-config.yml` is:
```
- repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
```

Interestingly if I upgrade it to mypy 0.800 which is the latest those errors still don't appear.
If you can upgrade `.pre-commit-config.yml` to use mypy 0.800 and fix the pre-commit warnings in a PR that would be greatly appreciated.

**Comment by madhavajay** [comment]
I am closing this since A) the statement is incorrect and B) the mypy checks have been fixed and upgraded in another PR.

**Comment by Param-29** [comment]
I also noticed a similar issue. For both versions, `0.800` and `0.782`, I am getting the following error
Command: 
`pre-commit run --all-files`
Output 
```
Check python ast.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for added large files..............................................Passed
Check Yaml...............................................................Passed
Check for merge conflicts................................................Passed
Check that executables have shebangs.....................................Passed
Debug Statements (Python)................................................Passed
Tests should end in _test.py.............................................Passed
Fix requirements.txt.....................................................Passed
flake8...................................................................Passed
black....................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

src/syft/lib/python/bool.py:276: error: "bool" has no attribute "as_integer_ratio"
src/syft/lib/python/int.py:336: error: "as_integer_ratio" undefined in superclass
Found 2 errors in 2 files (checked 264 source files)

flynt....................................................................Passed
isort (python)...........................................................Passed

```

python3 version: `3.7.9`
PR that I am working on: #5131 

Note: CI uses python `3.8.7`
https://github.com/OpenMined/PySyft/pull/5157/checks?check_run_id=1911426541#step:7:83

**[WIP]: Updating python to `3.8.7`to check if python version is an issue.**

**Comment by madhavajay** [comment]
@Param-29 that is strange. I have installed Python 3.7.9 on macOS and I don't see that issue on your branch. If this is related to that specific version of Python and / or Ubuntu 20 we might see it when Ubuntu 20 is the default in GitHub CI. Until then perhaps continue with a different version or try to fix the issue that Mypy complains about and see if it passes in CI as well.

**Comment by Param-29** [comment]
@madhavajay As of now, I am continuing with a different version but would definitely like to explore the problem. 
Please run the following commands so that we could investigate if it is an OS issue (ubuntu) or a python version issue
```sh
conda create -n bug_5019 python=3.7.9
conda activate bug_5019
pip install pre-commit
pip install -e . 
pre-commit run --all-files 
```

This does give me the issue I mentioned above.

**Comment by iamtrask** [comment]
I am also getting the same error on python 3.7.9

```
error: "bool" has no attribute "as_integer_ratio"
```
